# Site settings
title: Spluxr

description: The tool for doing the things
  
# the subpath of your site, e.g. /blog/
baseurl: "" 

# the base hostname & protocol for your site
url: "http://jekyll-scroll.surge.sh"

# Build settings
markdown: kramdown

collections:
- sections

defaultColour: "#ffffff"

heroImage: "hero-image.jpg"